In [1]:
import pandas as pd

img_urls = pd.read_excel("../data/weddingwire_sample.xlsx")

In [2]:
img_urls

,URL,Title,VIP Mansion (1)-src,VIP Mansion (2)-src,VIP Mansion (3)-src,VIP Mansion (4)-src
0,https://www.weddingwire.com/biz/the-veranda-at...,Fairview Green River,https://cdn0.weddingwire.com/vendor/763100/3_2...,https://cdn0.weddingwire.com/vendor/763100/3_2...,https://cdn0.weddingwire.com/vendor/763100/3_2...,https://cdn0.weddingwire.com/vendor/763100/3_2...
1,https://www.weddingwire.com/biz/seacliff-count...,The Huntington Club,https://cdn0.weddingwire.com/vendor/283771/3_2...,https://cdn0.weddingwire.com/vendor/283771/3_2...,https://cdn0.weddingwire.com/vendor/283771/3_2...,https://cdn0.weddingwire.com/vendor/283771/3_2...
2,https://www.weddingwire.com/biz/sheraton-garde...,Sheraton Garden Grove South Anaheim,https://cdn0.weddingwire.com/vendor/204676/3_2...,https://cdn0.weddingwire.com/vendor/204676/3_2...,https://cdn0.weddingwire.com/vendor/204676/3_2...,https://cdn0.weddingwire.com/vendor/204676/3_2...
3,https://www.weddingwire.com/biz/tustin-ranch-g...,Tustin Ranch Golf Club,https://cdn0.weddingwire.com/vendor/466100/3_2...,https://cdn0.weddingwire.com/vendor/466100/3_2...,https://cdn0.weddingwire.com/vendor/466100/3_2...,https://cdn0.weddingwire.com/vendor/466100/3_2...
4,https://www.weddingwire.com/biz/orange-county-...,Orange County Mining Co.,https://cdn0.weddingwire.com/vendor/429061/3_2...,https://cdn0.weddingwire.com/vendor/429061/3_2...,https://cdn0.weddingwire.com/vendor/429061/3_2...,https://cdn0.weddingwire.com/vendor/429061/3_2...
5,https://www.weddingwire.com/biz/majestic-garde...,Majestic Garden Hotel,https://cdn0.weddingwire.com/vendor/229346/3_2...,https://cdn0.weddingwire.com/vendor/229346/3_2...,https://cdn0.weddingwire.com/vendor/229346/3_2...,https://cdn0.weddingwire.com/vendor/229346/3_2...
6,https://www.weddingwire.com/biz/los-coyotes-co...,Los Coyotes Country Club,https://cdn0.weddingwire.com/vendor/636310/3_2...,https://cdn0.weddingwire.com/vendor/636310/3_2...,https://cdn0.weddingwire.com/vendor/636310/3_2...,https://cdn0.weddingwire.com/vendor/636310/3_2...
7,https://www.weddingwire.com/biz/plaza-de-magda...,Plaza de Magdalena A Catering and Event Venue ...,https://cdn0.weddingwire.com/vendor/514267/3_2...,https://cdn0.weddingwire.com/vendor/514267/3_2...,https://cdn0.weddingwire.com/vendor/514267/3_2...,https://cdn0.weddingwire.com/vendor/514267/3_2...
8,https://www.weddingwire.com/biz/crossline-chur...,Crossline Church,https://cdn0.weddingwire.com/vendor/002702/3_2...,https://cdn0.weddingwire.com/vendor/002702/3_2...,https://cdn0.weddingwire.com/vendor/002702/3_2...,https://cdn0.weddingwire.com/vendor/002702/3_2...
9,https://www.weddingwire.com/biz/doubletree-by-...,DoubleTree by Hilton Hotel Irvine -Spectrum,https://cdn0.weddingwire.com/vendor/848804/3_2...,https://cdn0.weddingwire.com/vendor/848804/3_2...,https://cdn0.weddingwire.com/vendor/848804/3_2...,https://cdn0.weddingwire.com/vendor/848804/3_2...
10,https://www.weddingwire.com/biz/la-petite-rose...,La Petite Rose,https://cdn0.weddingwire.com/vendor/017141/3_2...,https://cdn0.weddingwire.com/vendor/017141/3_2...,https://cdn0.weddingwire.com/vendor/017141/3_2...,https://cdn0.weddingwire.com/vendor/017141/3_2...
11,https://www.weddingwire.com/biz/dove-canyon-co...,Dove Canyon Courtyard,https://cdn0.weddingwire.com/vendor/425590/3_2...,https://cdn0.weddingwire.com/vendor/425590/3_2...,https://cdn0.weddingwire.com/vendor/425590/3_2...,https://cdn0.weddingwire.com/vendor/425590/3_2...
12,https://www.weddingwire.com/biz/the-vintage-ro...,The Vintage Rose,https://cdn0.weddingwire.com/vendor/004906/3_2...,https://cdn0.weddingwire.com/vendor/004906/3_2...,https://cdn0.weddingwire.com/vendor/004906/3_2...,https://cdn0.weddingwire.com/vendor/004906/3_2...
13,https://www.weddingwire.com/biz/alta-vista-cou...,Alta Vista Country Club,https://cdn0.weddingwire.com/vendor/590811/3_2...,https://cdn0.weddingwire.com/vendor/590811/3_2...,https://cdn0.weddingwire.com/vendor/590811/3_2...,https://cdn0.weddingwire.com/vendor/590811/3_2...
14,https://www.weddingwire.com/biz/the-fifth-oc-a...,The FIFTH OC,https://cdn0.weddingwire.com/vendor/424049/3_2...,https://cdn0.weddingwire.com/vendor/424049/3_2...,https://cdn0.weddingwire.com/vendor/424049/3_2...,https://cdn0.weddingwire.com/vendor/424049/3_2...
15,https://www.weddingwire.com/biz/ebell-of-santa...,Ebell of Santa Ana,https://cdn0.weddingwire.com/vendor/232800/3_2...,https://cdn0.weddingwire.com/vendor/232800/3_2...,https://cdn0.weddingwire.com/vendor/232800/3_2...,https://cdn0.weddingwire.com/vendor/232800/3_2...
16,https://www.weddingwire.com/biz/wedgewood-wedd...,University Club by Wedgewood Weddings,https://cdn0.weddingwire.com/vendor/119099/3_2...,https://cdn0.weddingwire.com/vendor/119099/3_2...,https://cdn0.weddingwire.com/vendor/119099/3_2...,https://cdn0.weddingwire.com/vendor/119099/3_2...
17,https://www.weddingwire.com/biz/occasions-at-l...,Occasions at Laguna Village,https://cdn0.weddingwire.com/vendor/484240/3_2...,https://cdn0.weddingwire.com/vendor/484240/3_2...,https://cdn0.weddingwire.com/vendor/484240/3_2...,https://cdn0.weddingwire.com/vendor/484240/3_2...
18,https://www.weddingwire.com/biz/hyatt-regency-...,Hyatt Regency Orange County,https://cdn0.weddingwire.com/vendor/483003/3_2...,https://cdn0.weddingwire.com/vendor/483003/3_2...,https://cdn0.weddingwire.com/vendor/483003/3_2...,https://cdn0.weddingwire.com/vendor/483003/3_2...
19,https://www.weddingwire.com/biz/orange-county-...,Orange County Museum of Art,https://cdn0.weddingwire.com/vendor/460320/3_2...,https://cdn0.weddingwire.com/vendor/460320/3_2...,https://cdn0.weddingwire.com/vendor/460320/3_2...,https://cdn0.weddingwire.com/vendor/460320/3_2...
20,https://www.weddingwire.com/biz/the-westin-ana...,The Westin Anaheim Resort,https://cdn0.weddingwire.com/vendor/924479/3_2...,https://cdn0.weddingwire.com/vendor/924479/3_2...,https://cdn0.weddingwire.com/vendor/924479/3_2...,https://cdn0.weddingwire.com/vendor/924479/3_2...
21,https://www.weddingwire.com/biz/pasea-hotel-sp...,Paséa Hotel & Spa,https://cdn0.weddingwire.com/vendor/421147/3_2...,https://cdn0.weddingwire.com/vendor/421147/3_2...,https://cdn0.weddingwire.com/vendor/421147/3_2...,https://cdn0.weddingwire.com/vendor/421147/3_2...
22,https://www.weddingwire.com/biz/temecula-creek...,Temecula Creek Inn,https://cdn0.weddingwire.com/vendor/608820/3_2...,https://cdn0.weddingwire.com/vendor/608820/3_2...,https://cdn0.weddingwire.com/vendor/608820/3_2...,https://cdn0.weddingwire.com/vendor/608820/3_2...
23,https://www.weddingwire.com/biz/the-red-horse-...,The Red Horse Barn,https://cdn0.weddingwire.com/vendor/652150/3_2...,https://cdn0.weddingwire.com/vendor/652150/3_2...,https://cdn0.weddingwire.com/vendor/652150/3_2...,https://cdn0.weddingwire.com/vendor/652150/3_2...
24,https://www.weddingwire.com/biz/la-ventura-eve...,La Ventura Event Center,https://cdn0.weddingwire.com/vendor/916079/3_2...,https://cdn0.weddingwire.com/vendor/916079/3_2...,https://cdn0.weddingwire.com/vendor/916079/3_2...,https://cdn0.weddingwire.com/vendor/916079/3_2...
25,https://www.weddingwire.com/biz/avenue-of-the-...,Avenue of the Arts Costa Mesa,https://cdn0.weddingwire.com/vendor/474420/3_2...,https://cdn0.weddingwire.com/vendor/474420/3_2...,https://cdn0.weddingwire.com/vendor/474420/3_2...,https://cdn0.weddingwire.com/vendor/474420/3_2...
26,https://www.weddingwire.com/biz/inn-at-the-mis...,Inn at the Mission San Juan Capistrano,https://cdn0.weddingwire.com/vendor/537470/3_2...,https://cdn0.weddingwire.com/vendor/537470/3_2...,https://cdn0.weddingwire.com/vendor/537470/3_2...,https://cdn0.weddingwire.com/vendor/537470/3_2...
27,https://www.weddingwire.com/biz/hotel-zessa-a-...,"Hotel Zessa, a DoubleTree by Hilton",https://cdn0.weddingwire.com/vendor/581691/3_2...,https://cdn0.weddingwire.com/vendor/581691/3_2...,https://cdn0.weddingwire.com/vendor/581691/3_2...,https://cdn0.weddingwire.com/vendor/581691/3_2...
28,https://www.weddingwire.com/biz/pendry-newport...,Pendry Newport Beach,https://cdn0.weddingwire.com/vendor/688881/3_2...,https://cdn0.weddingwire.com/vendor/688881/3_2...,https://cdn0.weddingwire.com/vendor/688881/3_2...,https://cdn0.weddingwire.com/vendor/688881/3_2...
29,https://www.weddingwire.com/biz/the-hacienda-s...,The Hacienda,https://cdn0.weddingwire.com/vendor/233931/3_2...,https://cdn0.weddingwire.com/vendor/233931/3_2...,https://cdn0.weddingwire.com/vendor/233931/3_2...,https://cdn0.weddingwire.com/vendor/233931/3_2...

In [10]:
import pandas as pd

venue_info = pd.read_excel("../data/raw/Wedding Venues.xlsx")
venue_info[["Website ", "Venue name"]]

,Website,Venue name
0,https://94thsandiego.com/,94th Aero Squadron Restaurant
1,https://www.aocwinebar.com/brentwood,a.o.c. Brentwood
2,https://acehotel.com/palm-springs/,Ace Hotel & Swim Club
3,https://www.aguahedionda.org/,Agua Hedionda Nature Center
4,https://sbparksandrec.santabarbaraca.gov/venue...,Carousel House Santa Barbara
...,...,...
404,http://www.whitehouseeventcenter.com/,White House Banquets & Event Center
405,https://www.willowwoodspark.com/,Willow Woods Park
406,https://www.wilsoncreekwinery.com/weddings/,Wilson Creek Winery & Vineyards
407,https://www.woodlandhillscc.org/membership,Woodland Hills Country Club
408,https://yamashirohollywood.com/,Yamashiro Hollywood

In [11]:
import re
from pathlib import Path

import numpy as np

pdf_dir = Path("../data/raw/Southern California Wedding Venues")
pdf_files = [f.name.replace(".pdf", "") for f in pdf_dir.glob("*.pdf")]

clean_words = [
    "&",
    "the",
    "-",
    "ratesheet",
    "_",
    r"\(",
    r"\)",
    r"\.",
    "merged",
    "pricing",
    r"\d+",
    r"\.pdf",
    "packages",
    "brochure",
    "rate",
    "sheet",
    "information",
    "venue",
    "prices",
    "weddings",
    "wedding",
    "resort",
    "inclusive",
    "package",
    "digital",
    "guide",
    "park",
    "course",
    "golf",
    "banquets",
    "banquet",
    "restaurant",
    "catering",
    "event",
    "planner",
    "garden",
    "hotel",
    "spa",
    "at",
    "santa barbara",
    "santa monica",
    "santa maria",
    "san",
    "marino",
    "diego",
    "los",
    "angeles",
    "and",
    "or",
    "the",
    "of",
    "in",
    "at",
    "to",
    "from",
    "juan",
]


def _clean(name):
    for word in clean_words:
        name = re.sub(word, " ", name.lower())
    name = re.sub(" +", " ", name)
    return name


def _count_overlapping_words(name, venues):
    clean_venues = [_clean(venue) for venue in venues]
    clean_name = _clean(name)
    return [
        sum([word in clean_venue for word in clean_name.split(" ")])
        / len(clean_name.split(" "))
        for clean_venue in clean_venues
    ]


def _find_best_venue(name, venues):
    scores = _count_overlapping_words(name, venues)
    idx = np.argmax(scores)
    return venues[idx], scores[idx]


venues = venue_info["Venue name"].str.lower().tolist()
venues = [_clean(v) for v in venues]
clean_pdf_files = [_clean(f) for f in pdf_files]

df = pd.DataFrame()

df["pdf_name"] = clean_pdf_files
df["og_pdf_name"] = pdf_files
df["venue"], df["ratio"] = zip(*[_find_best_venue(f, venues) for f in pdf_files])
df

,pdf_name,og_pdf_name,venue,ratio
0,"saguaro, palm spr gs","The Saguaro, Palm Springs","saguaro, palm spr gs",1.0
1,carousel house,Carousel House Santa Barbara,carousel house,1.0
2,beverly hills presbyterian church,Beverly Hills Presbyterian Church,beverly hills presbyterian church,1.0
3,europa village,Europa Village,europa village,1.0
4,diamond bar,Diamond Bar Golf Course,diamond bar center,1.0
...,...,...,...,...
276,agua hedionda n ure center,Agua Hedionda Nature Center,agua hedionda n ure center,1.0
277,hills club,San Juan Hills Golf Club,friendly hills country club,1.0
278,canopy grove wedgewood,Canopy Grove Wedgewood,canopy grove wedgewood,1.0
279,pen sula beverly hills,The Peninsula Beverly Hills,pen sula beverly hills,1.0
280,a o c brentwood,a.o.c. Brentwood,a o c brentwood,1.0

In [8]:
(df[df["ratio"] < 0.8]["og_pdf_name"] + ".pdf").to_csv(
    "../data/processed/bad_pdfs.csv", index=False
)

In [12]:
(df[df["ratio"] < 0.8])

,pdf_name,og_pdf_name,venue,ratio
96,grace e simmons lodge,Grace E Simmons Lodge,grace e simons lodge,0.750000
102,glend a country club,Glendora Country Club,aliso viejo country club,0.750000
154,ace palm spr gs,Ace Hotel Palm Springs,alcazar palm spr gs,0.750000
181,villadeam e,Villadeamore,th aero squadron,0.500000
207,lakehouse polo club,Lakehouse Polo Club,lakeside polo club,0.666667

In [13]:
from itables import show

show(df[["pdf_name", "venue", "ratio"]])

In [11]:
1 - 50 / 281

0.8220640569395018

In [8]:
venue_info["Venue name"] = venue_info["Venue name"].apply(_clean).tolist()

In [9]:
df = df.merge(
    venue_info[["Website ", "Venue name"]],
    left_on="venue",
    right_on="Venue name",
    how="left",
    suffixes=("", ""),
).drop(columns=["Venue name"])
df

,pdf_name,venue,ratio,Website
0,sycuan casino,sycuan casino,1.00,https://www.sycuan.com/meet/
1,river s san diego,andaz san diego,0.80,http://www.andazsandiego.com
2,point san diego,andaz san diego,0.75,http://www.andazsandiego.com
3,cordiano winery,cordiano winery,1.00,https://www.cordianowinery.com/
4,aliso viejo wedgewood,aliso viejo by wedgewood,1.00,https://www.wedgewoodweddings.com/alisoviejo
...,...,...,...,...
284,alta vista,alta vista country club,1.00,https://www.altavistacc.com/weddings
285,la jolla beach tennis club,la jolla beach tennis club,1.00,https://www.ljbtc.com/
286,betty long beach,long beach museum of art,0.75,http://lbma.org/special-events/
287,san juan hills club,san juan hills club,1.00,http://www.sanjuanhillsgolf.com
288,lindley scott house,lindley scott house,1.00,http://www.lindleyscotthouse.com

In [10]:
import re

import numpy as np
from fuzzywuzzy import fuzz
from tqdm import tqdm


def clean_pdf_name(pdf_name):
    remove_words = [
        r"[\-_.&\d]",
        "events",
        ".pdf",
        "weddings",
        "wedding",
        "venue",
        "packages",
        "digital",
        "packet",
        "package",
        "ratesheet",
        "2024",
        "2025",
        "2023",
        "brochure",
    ]

    for word in remove_words:
        pdf_name = re.sub(word, "", pdf_name.lower())
    return pdf_name


venues = np.array([clean_pdf_name(v) for v in venue_info["Venue name"].tolist()])
df2 = pd.DataFrame()
for pdf in tqdm(pdf_files):
    clean_name = clean_pdf_name(pdf)
    ratios = [fuzz.partial_ratio(clean_name, venue) for venue in venues]
    max_ratio = np.max(ratios)
    max_idx = np.argmax(ratios)
    df2 = pd.concat(
        [
            df2,
            pd.DataFrame(
                {
                    "pdf_name": pdf,
                    "venue": venues[max_idx],
                    "url": venue_info["Website "].iloc[int(max_idx)],
                    "ratio": max_ratio,
                },
                index=[0],
            ),
        ]
    )
df2.sort_values(by="ratio", ascending=False)

100%|██████████| 289/289 [00:03<00:00, 86.33it/s]

,pdf_name,venue,url,ratio
0,Darlington House,darlington house,http://www.darlingtonhouse.org,100
0,malibu west beach club,malibu west beach club,https://www.malibuwestbeachclub.com/about,100
0,Republic Private Event Book,republic,https://republicvenue.com/,100
0,Point San Luis Lighthouse Keepers,point san luis lighthouse,https://www.pointsanluislighthouse.org/,100
0,dignity health sports park,dignity health sports,https://www.dignityhealthsportspark.com,100
...,...,...,...,...
0,Pasea-WeddingBrochure-2024-merged,paséa,https://www.paseahotel.com/,67
0,maderas poway,maderas club,https://www.maderasgolf.com/,67
0,CasaRomantica_BrideBook_2024,casa romantica cultural center s,https://www.casaromantica.org/,64
0,Dana Adobe-merged,la landmark,https://www.labanquets.com/venues/the-landmark...,55
0,2024 WEDDING PACKAGES,th aero squadron,https://94thsandiego.com/,50

In [11]:
df2

,pdf_name,venue,url,ratio
0,sycuan-casino-resort-wedding-packages,sycuan casino,https://www.sycuan.com/meet/,92
0,River Garden Weddings & Events San Diego-merged,river,https://csevenues.com/river-garden/,100
0,the point san diego,point,https://www.gettothepoint.io/,100
0,cordiano winery,cordiano winery,https://www.cordianowinery.com/,100
0,Pricing Packages Aliso Viejo Wedgewood Weddings,aliso viejo by wedgewood,https://www.wedgewoodweddings.com/alisoviejo,94
...,...,...,...,...
0,2025 Alta Vista Wedding Packages,alta vista country club,https://www.altavistacc.com/weddings,85
0,La Jolla Beach & Tennis Club-merged,club,https://www.parkclubca.com/,100
0,the betty long beach,westin long beach,http://www.theeveleigh.com/,80
0,San Juan Hills Golf Club,club,https://www.parkclubca.com/,100
0,Lindley-Scott House - 2024 Brochure,lindley scott house,http://www.lindleyscotthouse.com,95

In [14]:
show(df2)

In [ ]:
2023 Continental Catering Full Service Menu.pdf
andrei_s.pdf
2024 WEDDING PACKAGES.pdf
Dana Adobe-merged.pdf
CasaRomantica_BrideBook_2024.pdf
maderas poway.pdf
inn of the seventh ray.pdf

In [16]:
df2.sort_values(by="ratio", ascending=True)["pdf_name"].tolist()[:5]

['2024 WEDDING PACKAGES',
 'Dana Adobe-merged',
 'CasaRomantica_BrideBook_2024',
 'maderas poway',
 'inn of the seventh ray']

In [12]:
df["venue2"] = df2["venue"].values
df["ratio2"] = df2["ratio"].values
df["Website2"] = df2["url"].values
df["good"] = (df["Website "] == df["Website2"]) | (df["ratio"] > 0.8)
df["pdf_name"] = pdf_files
df.to_csv("../data/processed/pdf_to_url_using_excel_sheet.csv", index=False)

In [13]:
show(df[df["good"] == False])